### ISSUE TITLE
Visual glitches in Windows installer for the server

### ISSUE THREAD

**Issue by Mithil467** [jupyterlab/jupyterlab_app#210]
## Description

There is not enough space to complete the second paragraph. Also the logo seems to be cut at the end.

![image](https://user-images.githubusercontent.com/41439841/133547834-e8cc070d-6ea3-4202-879d-7850912484d6.png)

## Context

- Operating System and version: Windows 10
- JupyterLab version: Latest installer on github actions https://github.com/jupyterlab/jupyterlab_app/actions/runs/1239871781

**Comment by mbektas** [comment]
thanks for reporting this @Mithil467 . This installer UI is created by conda Constructor and we have limited control over it. I made titles shorter to fit in the linked PR. In order to change the text in the checkboxes we will have to customize NSIS installer fully but I don't think it is worth the effort at this time.
