### ISSUE TITLE
No "close" or "exit" option?

### ISSUE THREAD

**Issue by CarlosGrohmann** [jupyterlab/jupyterlab_app#235]
Is it just me or really there isn't a menu option to exit or close the app? It seems my only choice is to close all tabs and then close the window...

Tried both in Windows and in Ubuntu 21.04

**Comment by mbektas** [comment]
Hi @CarlosGrohmann . You shouldn't need to close the tabs you have open and closing the window (using close button on top right / top left) should close the App (after a confirmation dialog with Leave & Stay buttons is shown). If you have unsaved changes in tabs, it is better to save them first, otherwise you might lose unsaved work.

**Comment by CarlosGrohmann** [comment]
Ok, thanks. I was just wondering if that was the right way to do it.
