### ISSUE TITLE
Figure out how to propagate ENV VARs in packaged apps

### ISSUE THREAD

**Issue by ellisonbg** [jupyterlab/jupyterlab_app#55]
The ENV VARs in a user's environment determine which python and notebook server will be used. We will need to figure out a way of propagating the those to the electron app when installed so it can start the notebook server.

**Comment by ddavidebor** [comment]
It appears that applications launched from a .desktop shortcut on Linux do not see the ENV vars from the user's .bashrc.

The user should still be able to select which notebook server to use and save the preference. #48

**Comment by lucbouchard1** [comment]
I did some investigation on this, and the problem boils down to the user's PATH variable. Any extension to the path that is added by the .bashrc is not included when a program is executed from the desktop environment. Thus, if Jupyter is installed by Anaconda, the main process just can't find the executable and the app can't start.

I found a solution that works but could use some refinement. Instead of spawning the Jupyter notebook server directly from the main process, we can spawn a shell in interactive mode, which forces .bashrc to be executed. We then pipe a command to the shell that starts the notebook server.

**Comment by rgbkrk** [comment]
We use `shell-env` for this in nteract, with the huge caveat that you have to expect to only use what's in their default `$PATH` (no custom launching), since when you package the app on OS X it launches via `launchctl` when run from the dock / searchlight.

**Comment by ddavidebor** [comment]
This has been solved, hasn't it?
